// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240405.15

void* winrt_make_ControlSystem_MainWindow()
{
    return winrt::detach_abi(winrt::make<winrt::ControlSystem::factory_implementation::MainWindow>());
}
WINRT_EXPORT namespace winrt::ControlSystem
{
    MainWindow::MainWindow() :
        MainWindow(make<ControlSystem::implementation::MainWindow>())
    {
    }
}
