// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240405.15

#include "pch.h"
#include "winrt/base.h"
void* winrt_make_ControlSystem_MainPage();
void* winrt_make_ControlSystem_MainWindow();
void* winrt_make_ControlSystem_Page1();
void* winrt_make_ControlSystem_Page2();
void* winrt_make_ControlSystem_Page3();
void* winrt_make_ControlSystem_Page4();
void* winrt_make_ControlSystem_ParameterSet();
void* winrt_make_ControlSystem_SettingsPage();
void* winrt_make_ControlSystem_SimulationMultiThreading();
void* winrt_make_ControlSystem_XamlMetaDataProvider();

bool __stdcall winrt_can_unload_now() noexcept
{
    if (winrt::get_module_lock())
    {
        return false;
    }

    winrt::clear_factory_cache();
    return true;
}

void* __stdcall winrt_get_activation_factory([[maybe_unused]] std::wstring_view const& name)
{
    auto requal = [](std::wstring_view const& left, std::wstring_view const& right) noexcept
    {
        return std::equal(left.rbegin(), left.rend(), right.rbegin(), right.rend());
    };

    if (requal(name, L"ControlSystem.MainPage"))
    {
        return winrt_make_ControlSystem_MainPage();
    }

    if (requal(name, L"ControlSystem.MainWindow"))
    {
        return winrt_make_ControlSystem_MainWindow();
    }

    if (requal(name, L"ControlSystem.Page1"))
    {
        return winrt_make_ControlSystem_Page1();
    }

    if (requal(name, L"ControlSystem.Page2"))
    {
        return winrt_make_ControlSystem_Page2();
    }

    if (requal(name, L"ControlSystem.Page3"))
    {
        return winrt_make_ControlSystem_Page3();
    }

    if (requal(name, L"ControlSystem.Page4"))
    {
        return winrt_make_ControlSystem_Page4();
    }

    if (requal(name, L"ControlSystem.ParameterSet"))
    {
        return winrt_make_ControlSystem_ParameterSet();
    }

    if (requal(name, L"ControlSystem.SettingsPage"))
    {
        return winrt_make_ControlSystem_SettingsPage();
    }

    if (requal(name, L"ControlSystem.SimulationMultiThreading"))
    {
        return winrt_make_ControlSystem_SimulationMultiThreading();
    }

    if (requal(name, L"ControlSystem.XamlMetaDataProvider"))
    {
        return winrt_make_ControlSystem_XamlMetaDataProvider();
    }

    return nullptr;
}

int32_t __stdcall WINRT_CanUnloadNow() noexcept
{
#ifdef _WRL_MODULE_H_
    if (!::Microsoft::WRL::Module<::Microsoft::WRL::InProc>::GetModule().Terminate())
    {
        return 1;
    }
#endif

    return winrt_can_unload_now() ? 0 : 1;
}

int32_t __stdcall WINRT_GetActivationFactory(void* classId, void** factory) noexcept try
{
    std::wstring_view const name{ *reinterpret_cast<winrt::hstring*>(&classId) };
    *factory = winrt_get_activation_factory(name);

    if (*factory)
    {
        return 0;
    }

#ifdef _WRL_MODULE_H_
    return ::Microsoft::WRL::Module<::Microsoft::WRL::InProc>::GetModule().GetActivationFactory(static_cast<HSTRING>(classId), reinterpret_cast<::IActivationFactory**>(factory));
#else
    return winrt::hresult_class_not_available(name).to_abi();
#endif
}
catch (...) { return winrt::to_hresult(); }
