// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240405.15

void* winrt_make_ControlSystem_Page2()
{
    return winrt::detach_abi(winrt::make<winrt::ControlSystem::factory_implementation::Page2>());
}
WINRT_EXPORT namespace winrt::ControlSystem
{
    Page2::Page2() :
        Page2(make<ControlSystem::implementation::Page2>())
    {
    }
}
