// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240405.15

void* winrt_make_ControlSystem_Page1()
{
    return winrt::detach_abi(winrt::make<winrt::ControlSystem::factory_implementation::Page1>());
}
WINRT_EXPORT namespace winrt::ControlSystem
{
    Page1::Page1() :
        Page1(make<ControlSystem::implementation::Page1>())
    {
    }
}
