// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240405.15

void* winrt_make_ControlSystem_XamlMetaDataProvider()
{
    return winrt::detach_abi(winrt::make<winrt::ControlSystem::factory_implementation::XamlMetaDataProvider>());
}
WINRT_EXPORT namespace winrt::ControlSystem
{
    XamlMetaDataProvider::XamlMetaDataProvider() :
        XamlMetaDataProvider(make<ControlSystem::implementation::XamlMetaDataProvider>())
    {
    }
}
