
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once

#include <unknwn.h>

// Undefine GetCurrentTime macro to prevent
// conflict with Storyboard::GetCurrentTime
#undef GetCurrentTime

#if __has_include(<winrt/Microsoft.UI.Xaml.h>)
#include <winrt/Microsoft.UI.Xaml.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Controls.h>)
#include <winrt/Microsoft.UI.Xaml.Controls.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Markup.h>)
#include <winrt/Microsoft.UI.Xaml.Markup.h>
#endif


namespace winrt::ControlSystem::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct Page3T : public ::winrt::ControlSystem::implementation::Page3_base<D,
        ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector,
        I...>
    {
        using base_type = typename Page3T::base_type;
        using base_type::base_type;
        using class_type = typename Page3T::class_type;

        void InitializeComponent();
        virtual void Connect(int32_t connectionId, IInspectable const& target);
        virtual ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Microsoft::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Microsoft::UI::Xaml::Controls::Grid RootGrid()
        {
            return _RootGrid;
        }
        void RootGrid(::winrt::Microsoft::UI::Xaml::Controls::Grid value)
        {
            _RootGrid = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock PageHeader()
        {
            return _PageHeader;
        }
        void PageHeader(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _PageHeader = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ScrollViewer contentSV()
        {
            return _contentSV;
        }
        void contentSV(::winrt::Microsoft::UI::Xaml::Controls::ScrollViewer value)
        {
            _contentSV = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::InfoBar InformationBar()
        {
            return _InformationBar;
        }
        void InformationBar(::winrt::Microsoft::UI::Xaml::Controls::InfoBar value)
        {
            _InformationBar = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock Mytext()
        {
            return _Mytext;
        }
        void Mytext(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _Mytext = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::WebView2 MyWebView2()
        {
            return _MyWebView2;
        }
        void MyWebView2(::winrt::Microsoft::UI::Xaml::Controls::WebView2 value)
        {
            _MyWebView2 = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch Simulation_toggle_button()
        {
            return _Simulation_toggle_button;
        }
        void Simulation_toggle_button(::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch value)
        {
            _Simulation_toggle_button = value;
        }
        
    protected:
        bool _contentLoaded{false};

    private:
        struct Page3_obj1_Bindings;

        ::winrt::Microsoft::UI::Xaml::Controls::Grid _RootGrid{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _PageHeader{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ScrollViewer _contentSV{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::InfoBar _InformationBar{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _Mytext{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::WebView2 _MyWebView2{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch _Simulation_toggle_button{nullptr};
    };
}

