
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once

#include <unknwn.h>

// Undefine GetCurrentTime macro to prevent
// conflict with Storyboard::GetCurrentTime
#undef GetCurrentTime

#if __has_include(<winrt/Microsoft.UI.Xaml.Controls.h>)
#include <winrt/Microsoft.UI.Xaml.Controls.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Markup.h>)
#include <winrt/Microsoft.UI.Xaml.Markup.h>
#endif


namespace winrt::ControlSystem::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct Page4T : public ::winrt::ControlSystem::implementation::Page4_base<D,
        ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector,
        I...>
    {
        using base_type = typename Page4T::base_type;
        using base_type::base_type;
        using class_type = typename Page4T::class_type;

        void InitializeComponent();
        virtual void Connect(int32_t connectionId, IInspectable const& target);
        virtual ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Microsoft::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock PageHeader()
        {
            return _PageHeader;
        }
        void PageHeader(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _PageHeader = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Grid SourceElement()
        {
            return _SourceElement;
        }
        void SourceElement(::winrt::Microsoft::UI::Xaml::Controls::Grid value)
        {
            _SourceElement = value;
        }
        
    protected:
        bool _contentLoaded{false};

    private:
        struct Page4_obj1_Bindings;

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _PageHeader{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Grid _SourceElement{nullptr};
    };
}

