
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once

#include <unknwn.h>

// Undefine GetCurrentTime macro to prevent
// conflict with Storyboard::GetCurrentTime
#undef GetCurrentTime

#if __has_include(<winrt/Microsoft.UI.Xaml.h>)
#include <winrt/Microsoft.UI.Xaml.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Controls.h>)
#include <winrt/Microsoft.UI.Xaml.Controls.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Controls.Primitives.h>)
#include <winrt/Microsoft.UI.Xaml.Controls.Primitives.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Markup.h>)
#include <winrt/Microsoft.UI.Xaml.Markup.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Media.h>)
#include <winrt/Microsoft.UI.Xaml.Media.h>
#endif


namespace winrt::ControlSystem::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct Page1T : public ::winrt::ControlSystem::implementation::Page1_base<D,
        ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector,
        I...>
    {
        using base_type = typename Page1T::base_type;
        using base_type::base_type;
        using class_type = typename Page1T::class_type;

        void InitializeComponent();
        virtual void Connect(int32_t connectionId, IInspectable const& target);
        virtual ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Microsoft::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Microsoft::UI::Xaml::Media::LinearGradientBrush BackgroundGradient()
        {
            return _BackgroundGradient;
        }
        void BackgroundGradient(::winrt::Microsoft::UI::Xaml::Media::LinearGradientBrush value)
        {
            _BackgroundGradient = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Grid HeaderGrid()
        {
            return _HeaderGrid;
        }
        void HeaderGrid(::winrt::Microsoft::UI::Xaml::Controls::Grid value)
        {
            _HeaderGrid = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Grid ImageGrid()
        {
            return _ImageGrid;
        }
        void ImageGrid(::winrt::Microsoft::UI::Xaml::Controls::Grid value)
        {
            _ImageGrid = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ScrollView SelectCard()
        {
            return _SelectCard;
        }
        void SelectCard(::winrt::Microsoft::UI::Xaml::Controls::ScrollView value)
        {
            _SelectCard = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button Parameter_Set()
        {
            return _Parameter_Set;
        }
        void Parameter_Set(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _Parameter_Set = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button Select_Mode_Fixed()
        {
            return _Select_Mode_Fixed;
        }
        void Select_Mode_Fixed(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _Select_Mode_Fixed = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button Select_Mode_Real_Time()
        {
            return _Select_Mode_Real_Time;
        }
        void Select_Mode_Real_Time(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _Select_Mode_Real_Time = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button ToPage3()
        {
            return _ToPage3;
        }
        void ToPage3(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _ToPage3 = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::HyperlinkButton Learn_About_CMG()
        {
            return _Learn_About_CMG;
        }
        void Learn_About_CMG(::winrt::Microsoft::UI::Xaml::Controls::HyperlinkButton value)
        {
            _Learn_About_CMG = value;
        }
        
    protected:
        bool _contentLoaded{false};

    private:
        struct Page1_obj1_Bindings;

        ::winrt::Microsoft::UI::Xaml::Media::LinearGradientBrush _BackgroundGradient{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Grid _HeaderGrid{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Grid _ImageGrid{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ScrollView _SelectCard{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _Parameter_Set{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _Select_Mode_Fixed{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _Select_Mode_Real_Time{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _ToPage3{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::HyperlinkButton _Learn_About_CMG{nullptr};
    };
}

