
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once

#include <unknwn.h>

// Undefine GetCurrentTime macro to prevent
// conflict with Storyboard::GetCurrentTime
#undef GetCurrentTime

#if __has_include(<winrt/Microsoft.UI.Xaml.h>)
#include <winrt/Microsoft.UI.Xaml.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Controls.h>)
#include <winrt/Microsoft.UI.Xaml.Controls.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Controls.Primitives.h>)
#include <winrt/Microsoft.UI.Xaml.Controls.Primitives.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Markup.h>)
#include <winrt/Microsoft.UI.Xaml.Markup.h>
#endif


namespace winrt::ControlSystem::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct ParameterSetT : public ::winrt::ControlSystem::implementation::ParameterSet_base<D,
        ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector,
        I...>
    {
        using base_type = typename ParameterSetT::base_type;
        using base_type::base_type;
        using class_type = typename ParameterSetT::class_type;

        void InitializeComponent();
        virtual void Connect(int32_t connectionId, IInspectable const& target);
        virtual ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Microsoft::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Microsoft::UI::Xaml::Controls::Grid RootGrid()
        {
            return _RootGrid;
        }
        void RootGrid(::winrt::Microsoft::UI::Xaml::Controls::Grid value)
        {
            _RootGrid = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button BackwardButton()
        {
            return _BackwardButton;
        }
        void BackwardButton(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _BackwardButton = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock PageHeader()
        {
            return _PageHeader;
        }
        void PageHeader(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _PageHeader = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ScrollViewer contentSV()
        {
            return _contentSV;
        }
        void contentSV(::winrt::Microsoft::UI::Xaml::Controls::ScrollViewer value)
        {
            _contentSV = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Expander Expander6()
        {
            return _Expander6;
        }
        void Expander6(::winrt::Microsoft::UI::Xaml::Controls::Expander value)
        {
            _Expander6 = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Expander Expander1()
        {
            return _Expander1;
        }
        void Expander1(::winrt::Microsoft::UI::Xaml::Controls::Expander value)
        {
            _Expander1 = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Expander Expander2()
        {
            return _Expander2;
        }
        void Expander2(::winrt::Microsoft::UI::Xaml::Controls::Expander value)
        {
            _Expander2 = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock BackwardButtonText()
        {
            return _BackwardButtonText;
        }
        void BackwardButtonText(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _BackwardButtonText = value;
        }
        
    protected:
        bool _contentLoaded{false};

    private:
        struct ParameterSet_obj1_Bindings;

        ::winrt::Microsoft::UI::Xaml::Controls::Grid _RootGrid{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _BackwardButton{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _PageHeader{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ScrollViewer _contentSV{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Expander _Expander6{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Expander _Expander1{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Expander _Expander2{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _BackwardButtonText{nullptr};
    };
}

