
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once

#include <unknwn.h>

// Undefine GetCurrentTime macro to prevent
// conflict with Storyboard::GetCurrentTime
#undef GetCurrentTime

#if __has_include(<winrt/Microsoft.UI.Xaml.Controls.h>)
#include <winrt/Microsoft.UI.Xaml.Controls.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Controls.Primitives.h>)
#include <winrt/Microsoft.UI.Xaml.Controls.Primitives.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Markup.h>)
#include <winrt/Microsoft.UI.Xaml.Markup.h>
#endif


namespace winrt::ControlSystem::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct SettingsPageT : public ::winrt::ControlSystem::implementation::SettingsPage_base<D,
        ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector,
        I...>
    {
        using base_type = typename SettingsPageT::base_type;
        using base_type::base_type;
        using class_type = typename SettingsPageT::class_type;

        void InitializeComponent();
        virtual void Connect(int32_t connectionId, IInspectable const& target);
        virtual ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Microsoft::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Microsoft::UI::Xaml::Controls::Grid RootGrid()
        {
            return _RootGrid;
        }
        void RootGrid(::winrt::Microsoft::UI::Xaml::Controls::Grid value)
        {
            _RootGrid = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock PageHeader()
        {
            return _PageHeader;
        }
        void PageHeader(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _PageHeader = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ScrollViewer contentSV()
        {
            return _contentSV;
        }
        void contentSV(::winrt::Microsoft::UI::Xaml::Controls::ScrollViewer value)
        {
            _contentSV = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Expander Expander1()
        {
            return _Expander1;
        }
        void Expander1(::winrt::Microsoft::UI::Xaml::Controls::Expander value)
        {
            _Expander1 = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ImageIcon Icon_about()
        {
            return _Icon_about;
        }
        void Icon_about(::winrt::Microsoft::UI::Xaml::Controls::ImageIcon value)
        {
            _Icon_about = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock text_about()
        {
            return _text_about;
        }
        void text_about(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _text_about = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Grid SettingsPage_About1()
        {
            return _SettingsPage_About1;
        }
        void SettingsPage_About1(::winrt::Microsoft::UI::Xaml::Controls::Grid value)
        {
            _SettingsPage_About1 = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Grid SettingsPage_About2()
        {
            return _SettingsPage_About2;
        }
        void SettingsPage_About2(::winrt::Microsoft::UI::Xaml::Controls::Grid value)
        {
            _SettingsPage_About2 = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Grid SettingsPage_About3()
        {
            return _SettingsPage_About3;
        }
        void SettingsPage_About3(::winrt::Microsoft::UI::Xaml::Controls::Grid value)
        {
            _SettingsPage_About3 = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock SettingsPage_Thanks()
        {
            return _SettingsPage_Thanks;
        }
        void SettingsPage_Thanks(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _SettingsPage_Thanks = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock SettingsPage_Dependicies()
        {
            return _SettingsPage_Dependicies;
        }
        void SettingsPage_Dependicies(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _SettingsPage_Dependicies = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock SettingsPage_About_author()
        {
            return _SettingsPage_About_author;
        }
        void SettingsPage_About_author(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _SettingsPage_About_author = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Grid SelectItem1()
        {
            return _SelectItem1;
        }
        void SelectItem1(::winrt::Microsoft::UI::Xaml::Controls::Grid value)
        {
            _SelectItem1 = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Grid SelectItem2()
        {
            return _SelectItem2;
        }
        void SelectItem2(::winrt::Microsoft::UI::Xaml::Controls::Grid value)
        {
            _SelectItem2 = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox navigationLocation()
        {
            return _navigationLocation;
        }
        void navigationLocation(::winrt::Microsoft::UI::Xaml::Controls::ComboBox value)
        {
            _navigationLocation = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ImageIcon Icon_test()
        {
            return _Icon_test;
        }
        void Icon_test(::winrt::Microsoft::UI::Xaml::Controls::ImageIcon value)
        {
            _Icon_test = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock Text_test2()
        {
            return _Text_test2;
        }
        void Text_test2(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _Text_test2 = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox navigation1()
        {
            return _navigation1;
        }
        void navigation1(::winrt::Microsoft::UI::Xaml::Controls::ComboBox value)
        {
            _navigation1 = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ImageIcon Icon_test0()
        {
            return _Icon_test0;
        }
        void Icon_test0(::winrt::Microsoft::UI::Xaml::Controls::ImageIcon value)
        {
            _Icon_test0 = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock Text_test1()
        {
            return _Text_test1;
        }
        void Text_test1(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _Text_test1 = value;
        }
        
    protected:
        bool _contentLoaded{false};

    private:
        struct SettingsPage_obj1_Bindings;

        ::winrt::Microsoft::UI::Xaml::Controls::Grid _RootGrid{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _PageHeader{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ScrollViewer _contentSV{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Expander _Expander1{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ImageIcon _Icon_about{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _text_about{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Grid _SettingsPage_About1{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Grid _SettingsPage_About2{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Grid _SettingsPage_About3{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _SettingsPage_Thanks{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _SettingsPage_Dependicies{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _SettingsPage_About_author{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Grid _SelectItem1{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Grid _SelectItem2{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox _navigationLocation{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ImageIcon _Icon_test{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _Text_test2{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox _navigation1{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ImageIcon _Icon_test0{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _Text_test1{nullptr};
    };
}

